# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CourseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CourseProject
pod 'GoogleAPIClientForREST/Sheets', '~> 1.2.1'
    pod 'GoogleSignIn', '~> 4.1.1'
	pod 'RealmSwift'
pod 'DLRadioButton'
pod 'BetterSegmentedControl', '~> 0.9'
    pod 'ILPDFKit'



end
